### ISSUE TITLE
Request: Docker or Linux version

### ISSUE THREAD

**Issue by stefanheijnen** [CryptoGnome/Bybit-Bot#1]
Hi CryptoGnome. Would it be possible to create a Linux or Docker version of your bybit bot?

**Comment by keepasa** [comment]
Would like this also.  I see that Node JS app already has linux binaries (Mac also) on the main site.
https://nodejs.org/en/download/

So I guess if we can get that to work / install, then we just have to deal with the bybit-lick.exe.  I'm wondering if that would run on linux wine (windows emulator).

Just thought I'd throw that in to see if any possibility in future etc..
