### ISSUE TITLE
Lick Hunter TV VWAP indicator

### ISSUE THREAD

**Issue by Mistras88** [CryptoGnome/Bybit-Bot#14]
It would be great to have a TV VWAP indicator that exactly matches the Lick Hunter bots VWAP settings.   It's tough using indicators that provide a best guess.  It would allow users of the bot to better set their VWAP offsets and would significantly reduce the "Why didn't I get a trade" comments.

**Comment by CryptoGnome** [comment]
This is not possible at the moment.
