### ISSUE TITLE
Discord webhooks - differentiate between ETH and BTC alerts

### ISSUE THREAD

**Issue by Mistras88** [CryptoGnome/Bybit-Bot#4]
Hey guys - it's Spifire over in the CG Discord.    Hopefully this is an easy feature to implement - any way to insert 'ETH' or 'BTC' into the alerts that get sent to my Discord thru webhooks?   They all say the same thing so it's hard to tell quickly if it was ETH or BTC that hit.

Thanks!
Rob

**Comment by CryptoGnome** [comment]
I will push this in the next release!
